from abc import ABC, abstractmethod
from datetime import datetime
import asyncio
import aiomqtt
from typing import Optional

from src.domain.enums import CpStatus, MqttTopics
from src.domain.entities.charge_point import ChargePoint
from src.domain.entities.session import Session
from src.domain.entities.mqtt import MqttMessage

class ChargePointRepo(ABC):
    @abstractmethod
    def list_charge_points(self, status: Optional[CpStatus], limit: int = 10, offset: int = 0) -> list[ChargePoint]: ...
    @abstractmethod
    def get_charge_point(self, id: str) -> ChargePoint: ...
    @abstractmethod
    def create_charge_point(self, cp: ChargePoint) -> ChargePoint: ...
    @abstractmethod
    def update_charge_point(self, cp: ChargePoint) -> ChargePoint: ...
    @abstractmethod
    def remove_charge_point(self, id: str) -> None: ...
    @abstractmethod
    def update_charge_point_status(self, id: str, status: CpStatus) -> ChargePoint: ...
    @abstractmethod
    def update_charge_point_last_seen(self, id: str, last_seen: Optional[datetime]) -> ChargePoint: ...
    @abstractmethod
    def exists_charge_point(self, id: str) -> bool: ...

class SessionRepo(ABC):
    @abstractmethod
    def create_session(self, session: Session) -> Session: ...
    @abstractmethod
    def update_session(self, session: Session) -> Session: ...
    @abstractmethod
    def remove_session(self, id: str) -> None: ...
    @abstractmethod
    def get_session(self, id: str) -> Session: ...
    @abstractmethod
    def get_session_by_cp_id(self, cp_id: str) -> Session: ...
    @abstractmethod
    def list_sessions(self, cp_id: Optional[str], active: Optional[bool], limit: int = 10, offset: int = 0) -> list[Session]: ...
    @abstractmethod
    def stop_session(self, id: str) -> None: ...
    @abstractmethod
    def exists_session(self, id: str) -> bool: ...

class MqttConnectionRepo(ABC):
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def disconnect(self) -> None: ...
    @abstractmethod
    def is_connected(self) -> bool: ...
    @abstractmethod
    def get_client(self) -> aiomqtt.Client: ...

class MqttPublisherRepo(ABC):
    @abstractmethod
    def publish_message(self, message: MqttMessage) -> None: ...
    @abstractmethod
    def start_producer_loop(self) -> None: ...
    @abstractmethod
    def stop_producer_loop(self) -> None: ...
    @abstractmethod
    def get_publish_queue(self) -> asyncio.Queue: ...

class MqttSubscriberRepo(ABC):
    @abstractmethod
    def subscribe_to_topic(self, topic: MqttTopics) -> None: ...
    @abstractmethod
    def unsubscribe_from_topic(self, topic: MqttTopics) -> None: ...
    @abstractmethod
    def start_consumer_loop(self) -> None: ...
    @abstractmethod
    def stop_consumer_loop(self) -> None: ...
    @abstractmethod
    def get_subscribe_queue(self) -> asyncio.Queue: ...